import assert from 'node:assert/strict';
import { NullEngine } from '@babylonjs/core/Engines/nullEngine';
import { Scene } from '@babylonjs/core/scene';
import { Mesh } from '@babylonjs/core/Meshes/mesh';
import { PBRMaterial } from '@babylonjs/core/Materials/PBR/pbrMaterial';
import { Color3, Color4 } from '@babylonjs/core/Maths/math.color';
import { createEmberrageGlow } from '../web/emberrage-glow.js';

const engine = new NullEngine();
const scene = new Scene(engine);
const mesh = new Mesh('Equipped_Emberrage', scene);
const other = new Mesh('Other_avatar', scene);
const flame = new PBRMaterial('Emberrage_glow', scene);
flame.emissiveColor = new Color3(1, .001, .001);
const steel = new PBRMaterial('Emberrage_plate', scene);
const effect = createEmberrageGlow(scene, [mesh]);
assert(effect.layer.isEnabled);
assert(effect.layer.hasMesh(mesh));
assert(!effect.layer.hasMesh(other));
const color = new Color4();
effect.layer.customEmissiveColorSelector!(mesh, null!, flame, color);
assert(color.r === 1 && color.g < .01);
effect.layer.customEmissiveColorSelector!(mesh, null!, steel, color);
assert.equal(color.a, 0);
effect.setMeshes([]);
assert(!effect.layer.isEnabled, 'No equipped item must disable the whole layer');
effect.setMeshes([mesh]);
scene.onBeforeRenderObservable.notifyObservers(scene);
assert(effect.layer.intensity >= .375 && effect.layer.intensity <= .525);
effect.dispose();
assert(!scene.effectLayers.includes(effect.layer));
scene.dispose(); engine.dispose();
console.log('PASS per-item glow, red-only emission, empty equipment, pulse bounds and disposal');
