/**
 * G1 smoke test — world persistence (WorldManager save/load roundtrip).
 *
 * Mirrors C++ WorldManager::WriteFileDB/LoadFileDB semantics: worldTime,
 * generated zones and persistent ZDOs survive a restart; player positions
 * roundtrip through the players[] section (character ZDOs are excluded to
 * avoid ghosts). The critical regression guard: restored zones skip
 * generateZone, so the F4 terrain modifiers must be replayed on load —
 * otherwise location pieces float on slopes after every restart.
 *
 * Checks:
 *  1. Server A: generate zone (0,0) (StartTemple + foliage), set worldTime,
 *     inject a player → saveWorld writes a zstd envelope with the C++-shaped
 *     sections (meta/worldTime/zones/players/zdos); re-save rotates .prev.
 *  2. Fresh server B on the same worldsDir: loads worldTime, generated
 *     zones, all persistent ZDOs; spawn plateau is leveled again (F4
 *     modifier replayed); saved player state present; zones.update does
 *     NOT regenerate zone (0,0) (no duplicate pieces/proxy).
 *  3. Seed mismatch → load refused (fresh world).
 *  4. Corrupt save file → load refused (fresh world).
 *
 * Run: npx tsx server/test/g2-persistence.ts   (from the repo root)
 */

import { existsSync, readFileSync, writeFileSync, rmSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { zstdDecompressSync } from 'node:zlib';
import {
  TIME_DAY,
  FEATURES_BY_NAME,
  getTerrainLeveling,
  getStableHash,
} from '@wov/shared';
import { createWovServer } from '../src/WovServer.js';
import { SAVE_FORMAT_VERSION } from '../src/world/WorldManager.js';
import type { SavedPlayer, WorldSaveData } from '../src/world/WorldManager.js';

const f32 = Math.fround;
const __dirname = dirname(fileURLToPath(import.meta.url));
const WORLDS_DIR = resolve(__dirname, 'tmp-g2-worlds');
const SAVE_FILE = resolve(WORLDS_DIR, 'world.db.zst');
const SEED = 'KxSYuZquuw';

let failures = 0;
function check(name: string, cond: boolean, detail = ''): void {
  if (cond) {
    console.log(`  PASS ${name}${detail ? ` (${detail})` : ''}`);
  } else {
    console.error(`  FAIL ${name}${detail ? ` (${detail})` : ''}`);
    failures++;
  }
}

function makeServer(worldSeed: string) {
  return createWovServer({
    port: 2498, // never bound (init() only, no start()) — kept off the live ports anyway
    worldName: 'world',
    worldSeed,
    // book the StartTemple only (worldFeatures=false) — the worldwide
    // placement (~75s) is f2's job; generateZone gates tryGenerateFeature
    // behind worldFeatures, so the temple is generated via the exact
    // production path invoked directly below (f3 pattern).
    worldFeatures: false,
    worldVegetation: true, // real foliage ZDOs for the roundtrip
    worldsDir: WORLDS_DIR,
  });
}

console.log('=== G1 persistence smoke test ===');
rmSync(WORLDS_DIR, { recursive: true, force: true });

// ── [1] Server A: build a world state and save it ───────────────
console.log('\n[1] Server A: generate, modify, save:');
const serverA = makeServer(SEED);
serverA.init();

// The real generation path for zone (0,0): mark generated + foliage
// (generateZone) and temple pieces + F4 leveling (tryGenerateFeature).
const zonesA = serverA.zones as unknown as {
  generateZone(zone: { x: number; y: number }): boolean;
  tryGenerateFeature(zone: { x: number; y: number }): unknown;
};
check('zone (0,0) generated by production path', zonesA.generateZone({ x: 0, y: 0 }) === true);
zonesA.tryGenerateFeature({ x: 0, y: 0 });

const templeInst = serverA.zones.getFeatureInstance({ x: 0, y: 0 });
const templeLeveling = getTerrainLeveling(FEATURES_BY_NAME.get('StartTemple')!)!;
check(
  'StartTemple booked in zone (0,0)',
  templeInst !== undefined && templeInst.name === 'StartTemple'
);
const plateau = f32(templeInst!.pos.y + templeLeveling.levelOffset);
check(
  'A: spawn plateau leveled before save',
  serverA.getGroundHeight(0, 0) === plateau,
  `ground(0,0) ${serverA.getGroundHeight(0, 0)}, plateau ${plateau}`
);

// World modifications that must survive the restart
(serverA as unknown as { worldTime: number }).worldTime = 12345.5;
const savedViking: SavedPlayer = {
  name: 'TestViking',
  position: { x: 12.5, y: 37.25, z: -8.75 },
  flying: true,
};
(serverA as unknown as { savedPlayers: Map<string, SavedPlayer> }).savedPlayers.set(
  savedViking.name,
  savedViking
);

const persistentOnA = serverA.zdos
  .getAllZDOs()
  .filter((z) => serverA.prefabs.getByHash(z.prefabHash)?.isPersistent() ?? false).length;
check('A: persistent ZDOs present (foliage + temple)', persistentOnA > 0, `${persistentOnA}`);

serverA.saveWorld();
check('save file written', existsSync(SAVE_FILE), SAVE_FILE);

// Envelope shape (C++ .fwl meta + .db sections, JSON+zstd container)
const envelope = JSON.parse(zstdDecompressSync(readFileSync(SAVE_FILE)).toString('utf-8')) as WorldSaveData;
check(`envelope version ${SAVE_FORMAT_VERSION}`, envelope.version === SAVE_FORMAT_VERSION);
check(
  'meta carries world identity (C++ .fwl)',
  envelope.meta.worldName === 'world' &&
    envelope.meta.worldSeed === SEED &&
    envelope.meta.worldGenVersion === 2
);
check('worldTime saved', envelope.worldTime === 12345.5, `${envelope.worldTime}`);
check(
  'generated zones saved',
  envelope.zones.length === 1 && envelope.zones[0][0] === 0 && envelope.zones[0][1] === 0,
  JSON.stringify(envelope.zones)
);
check(
  'player saved with position + fly state',
  envelope.players.length === 1 &&
    envelope.players[0].name === 'TestViking' &&
    envelope.players[0].flying === true &&
    envelope.players[0].position.x === 12.5 &&
    envelope.players[0].position.y === 37.25 &&
    envelope.players[0].position.z === -8.75
);
check(
  'all persistent ZDOs saved',
  envelope.zdos.length === persistentOnA,
  `${envelope.zdos.length}/${persistentOnA}`
);
check(
  'no Player character ZDO in the save (ghost guard)',
  !envelope.zdos.some((z) => z.prefab === serverA.prefabs.getByName('Player')?.hash)
);

serverA.saveWorld(); // second save → backup rotation
check('previous save rotated to .prev (C++ backup)', existsSync(`${SAVE_FILE}.prev`));

// ── [2] Server B: fresh process, same worldsDir → load ──────────
console.log('\n[2] Server B: fresh server loads the save:');
const serverB = makeServer(SEED);
serverB.init();

check('B: worldTime restored', serverB.getWorldTime() === 12345.5, `${serverB.getWorldTime()}`);
check(
  'B: zone (0,0) restored as generated',
  serverB.zones.isZoneGenerated({ x: 0, y: 0 }) && serverB.zones.generatedZoneCount === 1,
  `${serverB.zones.generatedZoneCount} zone(s)`
);
check(
  'B: all persistent ZDOs restored',
  serverB.zdos.totalZDOCount === persistentOnA,
  `${serverB.zdos.totalZDOCount}/${persistentOnA}`
);
check(
  'B: F4 terrain modifier replayed (spawn plateau leveled after load)',
  serverB.getGroundHeight(0, 0) === plateau,
  `ground(0,0) ${serverB.getGroundHeight(0, 0)}, plateau ${plateau}`
);
const restoredViking = (
  serverB as unknown as { savedPlayers: Map<string, SavedPlayer> }
).savedPlayers.get('TestViking');
check(
  'B: player state restored',
  restoredViking !== undefined &&
    restoredViking.position.x === 12.5 &&
    restoredViking.position.y === 37.25 &&
    restoredViking.position.z === -8.75 &&
    restoredViking.flying === true
);

// A player standing in zone (0,0) must NOT trigger re-generation:
// zone (0,0)'s loaded ZDOs stay untouched (no duplicate temple pieces).
// G-POP: the generation queue is now sorted nearest-first, so the 200ms
// budget generates the DIRECT NEIGHBORS of (0,0) first — and their foliage
// groupRadius legitimately spills into ZDO-zone (0,0) (C++-faithful, see
// e2-vegetation). So instead of "count unchanged" we assert the loaded
// ZDO multiset is fully preserved (additions from neighbors are fine).
const proxyHash = getStableHash('LocationProxy');
const dumpZone = (): string[] =>
  serverB.zdos
    .getZDOsInZone({ x: 0, y: 0 })
    .map(
      (z) =>
        `${z.prefabHash}|${z.position.x.toFixed(3)},${z.position.y.toFixed(3)},${z.position.z.toFixed(3)}`
    )
    .sort();
const zoneZDOsBefore = dumpZone();
const proxiesBefore = serverB.zdos
  .getZDOsInZone({ x: 0, y: 0 })
  .filter((z) => z.prefabHash === proxyHash).length;
serverB.zones.update([{ x: 0, y: plateau, z: 0 }], 200);
const zoneZDOsAfter = dumpZone();
const proxiesAfter = serverB.zdos
  .getZDOsInZone({ x: 0, y: 0 })
  .filter((z) => z.prefabHash === proxyHash).length;
// multiset-subset: every loaded ZDO still present with at least its count
const afterCounts = new Map<string, number>();
for (const line of zoneZDOsAfter) afterCounts.set(line, (afterCounts.get(line) ?? 0) + 1);
let preserved = true;
const beforeCounts = new Map<string, number>();
for (const line of zoneZDOsBefore) beforeCounts.set(line, (beforeCounts.get(line) ?? 0) + 1);
for (const [line, n] of beforeCounts) {
  if ((afterCounts.get(line) ?? 0) < n) {
    preserved = false;
    break;
  }
}
check(
  'B: zones.update does not re-generate the restored zone',
  preserved && proxiesBefore === 1 && proxiesAfter === 1,
  `loaded ZDOs ${zoneZDOsBefore.length} preserved in ${zoneZDOsAfter.length} (neighbor spill ok), proxies ${proxiesBefore}→${proxiesAfter}`
);

// ── [3] Seed mismatch → load refused ─────────────────────────────
console.log('\n[3] Seed mismatch:');
const serverC = makeServer('TotallyDifferentSeed');
serverC.init();
check(
  'C: different seed starts fresh',
  serverC.zdos.totalZDOCount === 0 &&
    !serverC.zones.isZoneGenerated({ x: 0, y: 0 }) &&
    serverC.getWorldTime() === TIME_DAY
);

// ── [4] Corrupt save → load refused ──────────────────────────────
console.log('\n[4] Corrupt save file:');
writeFileSync(SAVE_FILE, Buffer.from('this is not a zstd stream'));
const serverD = makeServer(SEED);
serverD.init();
check(
  'D: corrupt save starts fresh',
  serverD.zdos.totalZDOCount === 0 &&
    !serverD.zones.isZoneGenerated({ x: 0, y: 0 }) &&
    serverD.getWorldTime() === TIME_DAY
);

rmSync(WORLDS_DIR, { recursive: true, force: true });

if (failures > 0) {
  console.error(`\n=== G1: ${failures} CHECK(S) FAILED ===`);
  process.exit(1);
}
console.log('\n=== G1: ALL PASSED ===');
